/**
 * Vite Configuration for @llm2ui/renderer NPM Package
 * 
 * Configures the build for ESM/CJS dual output with TypeScript declarations.
 * Supports tree-shaking and external peer dependencies.
 * 
 * Build outputs:
 * - ESM: dist/index.js, dist/react/index.js, dist/vue/index.js
 * - CJS: dist/index.cjs, dist/react/index.cjs, dist/vue/index.cjs
 * - Types: dist/index.d.ts, dist/react/index.d.ts, dist/vue/index.d.ts
 * 
 * Tree-shaking Configuration:
 * - sideEffects: false in package.json marks all modules as pure
 * - preserveModules: true keeps module structure for better tree-shaking
 * - moduleSideEffects: false tells bundlers modules have no side effects
 * - Pure annotations are preserved for dead code elimination
 * 
 * @see Requirements 13.1, 13.2, 13.3, 13.4
 */

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import dts from 'vite-plugin-dts';
import { resolve } from 'path';

// Root directory of the main project (for resolving src/sdk imports)
const rootDir = resolve(__dirname, '../..');
const packageDir = __dirname;

export default defineConfig({
  plugins: [
    react({
      // Use automatic JSX runtime for smaller bundle
      jsxRuntime: 'automatic',
    }),
    dts({
      // Include both local src and main project src for type generation
      include: [
        resolve(packageDir, 'src/**/*.ts'),
        resolve(packageDir, 'src/**/*.tsx'),
        resolve(rootDir, 'src/lib/**/*.ts'),
        resolve(rootDir, 'src/lib/**/*.tsx'),
        resolve(rootDir, 'src/types/**/*.ts'),
      ],
      // Exclude test files from type generation
      exclude: [
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/test/**',
      ],
      outDir: resolve(packageDir, 'dist'),
      // Disable rollup to avoid rootDir issues with monorepo structure
      rollupTypes: false,
      // Insert types entry in package.json exports
      insertTypesEntry: true,
      // Copy .d.ts files to output
      copyDtsFiles: true,
      // After build hook to log success
      afterBuild: () => {
        // Note: styles.css is now generated by build-styles.js script
        // which runs after vite build to include all Tailwind utilities
        console.log('✅ TypeScript declaration files generated successfully');
      },
    }),
  ],
  // Root directory for the build
  root: packageDir,
  // Enable esbuild optimizations for tree-shaking
  esbuild: {
    // Keep pure annotations for tree-shaking
    keepNames: false,
    // Remove console/debugger in production
    drop: process.env.NODE_ENV === 'production' ? ['console', 'debugger'] : [],
    // Pure functions that can be tree-shaken
    pure: ['console.log', 'console.info', 'console.debug'],
    // Minify identifiers for smaller output
    minifyIdentifiers: true,
    // Minify syntax
    minifySyntax: true,
    // Minify whitespace
    minifyWhitespace: true,
    // Tree-shaking friendly output
    treeShaking: true,
  },
  build: {
    lib: {
      // Multiple entry points for tree-shaking
      entry: {
        index: resolve(packageDir, 'src/index.ts'),
        'react/index': resolve(packageDir, 'src/react/index.ts'),
        'vue/index': resolve(packageDir, 'src/vue/index.ts'),
      },
      // Output both ESM and CJS formats
      formats: ['es', 'cjs'],
      // Custom file naming for dual package support
      fileName: (format, entryName) => {
        const ext = format === 'es' ? 'js' : 'cjs';
        return `${entryName}.${ext}`;
      },
    },
    rollupOptions: {
      // Externalize peer dependencies to avoid bundling them
      external: [
        // React ecosystem
        'react',
        'react-dom',
        'react-dom/client',
        'react/jsx-runtime',
        'react/jsx-dev-runtime',
        // Vue ecosystem
        'vue',
        // Radix UI components (peer dependencies)
        /^@radix-ui\/.*/,
        // Lucide icons - externalize for tree-shaking
        /^lucide-react$/,
        /^lucide-react\/.*/,
      ],
      output: {
        // Preserve exports for tree-shaking
        exports: 'named',
        // Ensure proper interop with CJS
        interop: 'auto',
        // Global variables for UMD/IIFE builds (if needed)
        globals: {
          'react': 'React',
          'react-dom': 'ReactDOM',
          'react-dom/client': 'ReactDOMClient',
          'react/jsx-runtime': 'jsxRuntime',
          'vue': 'Vue',
          'lucide-react': 'LucideReact',
        },
        // Preserve module structure for better tree-shaking
        preserveModules: true,
        preserveModulesRoot: resolve(packageDir, 'src'),
        // Chunk naming for better caching
        chunkFileNames: 'chunks/[name]-[hash].[format]',
      },
      // Enhanced treeshake options for smaller bundles
      treeshake: {
        // Remove unused exports aggressively
        moduleSideEffects: false,
        // Preserve pure annotations (/*#__PURE__*/)
        annotations: true,
        // Assume all property reads are side-effect free
        propertyReadSideEffects: false,
        // Try to determine if a function call has side effects
        tryCatchDeoptimization: false,
        // Assume unknown global variables don't have side effects
        unknownGlobalSideEffects: false,
        // Correctly handle getters with side effects
        correctVarValueBeforeDeclaration: false,
        // Preset for maximum tree-shaking
        preset: 'recommended',
      },
    },
    // Generate sourcemaps for debugging
    sourcemap: true,
    // Minify for production using esbuild (faster than terser)
    minify: 'esbuild',
    // Target modern browsers for smaller output
    target: 'es2020',
    // Output directory
    outDir: 'dist',
    // Clean output directory before build
    emptyOutDir: true,
    // Report compressed size
    reportCompressedSize: true,
    // CSS code splitting
    cssCodeSplit: true,
    // Chunk size warning limit (in kB)
    chunkSizeWarningLimit: 500,
    // Rollup options for better tree-shaking
    commonjsOptions: {
      // Transform CommonJS to ES modules for tree-shaking
      transformMixedEsModules: true,
      // Ignore conditional requires that can't be statically analyzed
      ignoreTryCatch: true,
    },
  },
  resolve: {
    alias: {
      // Alias for local src
      '@': resolve(rootDir, 'src'),
      // Alias to resolve main project imports
      '../../src': resolve(rootDir, 'src'),
      '../../../src': resolve(rootDir, 'src'),
      '../../../../src': resolve(rootDir, 'src'),
    },
  },
  // Optimize dependencies
  optimizeDeps: {
    include: [
      'clsx',
      'tailwind-merge',
      'class-variance-authority',
    ],
    exclude: [
      'react',
      'react-dom',
      'vue',
      'lucide-react',
    ],
  },
});
